import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import NavBar from './components/NavBar' // Import your NavBar component
import Footer from './components/Footer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'APT Meme Coin',
  description: 'Generated by apt meme coin',
  icons: {
    icon: "/images/png/logo.png", // ✅ Correct path
    shortcut: "/images/png/logo.png",
    apple: "/images/png/logo.png",
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className='mainDiv'>
          <NavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
